[[main]]
  identifier = "posts"
  name = "posts"
  url = "posts"
  weight = 1

[[main]]
  identifier = "notes"
  name = "notes"
  url = "notes"
  weight = 2

[[main]]
  identifier = "gallery"
  name = "gallery"
  url = "gallery"
  weight = 3
    
[[main]]
  parent = "gallery"
  name = "digital"
  url = "gallery/digital"

[[main]]
  parent = "gallery"
  name = "film"
  url = "gallery/film"

[[main]]
  identifier = "archive"
  name = "archive"
  url = "archive"
  weight = 4

[[main]]
  identifier = "about"
  name = "about"
  url = "about"
  weight = 5