[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 1

[[main]]
  identifier = "notes"
  name = "Notes"
  url = "notes"
  weight = 2

[[main]]
  identifier = "gallery"
  name = "Galleries"
  url = "gallery"
  weight = 3
    
[[main]]
  parent = "gallery"
  name = "Digital"
  url = "gallery/digital"

[[main]]
  parent = "gallery"
  name = "Film"
  url = "gallery/film"

[[main]]
  identifier = "archives"
  name = "Archives"
  url = "archives"
  weight = 4

[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 5