[[main]]
  identifier = "posts"
  name = "胡言"
  url = "posts"
  weight = 1

[[main]]
  identifier = "notes"
  name = "笔记"
  url = "notes"
  weight = 2

[[main]]
  identifier = "gallery"
  name = "影像"
  url = "gallery"
  weight = 3
    
[[main]]
  parent = "gallery"
  name = "数码"
  url = "gallery/digital"

[[main]]
  parent = "gallery"
  name = "胶片"
  url = "gallery/film"

[[main]]
  identifier = "archive"
  name = "归档"
  url = "archive"
  weight = 4

[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 5